### ISSUE TITLE
Doukmentation: Anzeige des Icos nur, wenn Werkzeugkasten Erweiterungswerkzeugliste angezeigt wird

### ISSUE THREAD

**Issue by Johann-Tree** [mrmap-community/gprlp_metadata_search#2]
Nach Installation der Erweiterung habe ich kein Icon zum Starten der Erweiterung gesehen. Erst nachdem ich nach langem Suchen die Erweiterungswerkzeugliste eingeblendet habe, war das Icon sichtbar. Bitte ergänzt die Dokumentation dementsprechend.

**Comment by armin11** [comment]
Done ;-)
