### ISSUE TITLE
Absturz QGIS 3.10.4 beim Laden eines zweiten Layers: corrupted double-linked list

### ISSUE THREAD

**Issue by Johann-Tree** [mrmap-community/gprlp_metadata_search#3]
Ich setze QGIS 3.10.4-A Coruña unter Ubuntu 20.04.4 LTS ein und habe eben die Erweiterung installiert. Als Bundesland habe ich Hessen ausgewählt. Das Laden einer Ressource in den Browser funktioniert. Wenn ich jedoch eine zweite Ressource laden möchte, stürzt QGIS reproduzierbar ab:
```
corrupted double-linked list
Abgebrochen (Speicherabzug geschrieben)
```
lautet die Fehlermeldung im Terminal.

**Comment by armin11** [comment]
Kannst du mal die genauen Ressourcen nennen, damit ich das nachstellen kann?

**Comment by armin11** [comment]
Seems to be obsolete now
