### ISSUE TITLE
Lizenz-Link führt ins Leere

### ISSUE THREAD

**Issue by MartinMap** [mrmap-community/gprlp_metadata_search#4]
Ein Klick auf "Open in Browser" um die Lizenz zu betrachten führt bei einigen Produkten ins Leere. Das Ausrufezeichen sagt da nicht viel.

![Selection_056](https://user-images.githubusercontent.com/6401482/220639717-e57b3894-339f-4ec5-b704-f1fa00949f05.png)

**Comment by armin11** [comment]
hi martin, danke für den hinweis - da ist wohl ein fehler beim mapbender28 - ich mach mal ein ticket auf: https://github.com/mrmap-community/Mapbender2.8/issues/113

**Comment by armin11** [comment]
das ist ein problem der schlecht ausgefüllten metadaten des jeweiligen datenanbieters. 

der verwaltungsgrenzen-metadatensatz hat keine weiteren infos:
https://www.geoportal.rlp.de/mapbender/php/mod_iso19139ToHtml.php?url=https%3A%2F%2Fwww.geoportal.rlp.de%2Fmapbender%2Fphp%2Fmod_dataISOMetadata.php%3FoutputFormat%3Diso19139%26id%3Dc553630d-6254-384b-1667-e42315feb142
der gemarkungs-metadatensatz aber schon:
https://www.geoportal.rlp.de/mapbender/php/mod_iso19139ToHtml.php?url=https%3A%2F%2Fwww.geoportal.rlp.de%2Fmapbender%2Fphp%2Fmod_dataISOMetadata.php%3FoutputFormat%3Diso19139%26id%3D79d8b001-972f-dc45-33ea-7d50113d4377

hier können wir nur schwer was machen  - ausser besser aufzuklären und die datenanbieter dazu anzuhalten, die lizenzinfos besser zu pflegen ;-)
